AppBundle\Entity\Movie:
  type: entity
  table: movie
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    title:
      type: string
      length: 255
    description:
      type: text
    director:
      type: string
      length: 255
    trailer:
      type: string
      length: 255
    length:
      type: integer
    released:
      type: integer
